# coding=utf-8

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage
from PIL import ImageTk, Image
import ctypes


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./two_dim_area_buttons")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


ctypes.windll.shcore.SetProcessDpiAwareness(3)

window = Tk()

window.geometry("900x600")
window.configure(bg = "#A5A5A5")


canvas = Canvas(
    window,
    bg = "#A5A5A5",
    height = 600,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=585.0,
    y=430.0,
    width=258.0,
    height=61.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=585.0,
    y=489.0,
    width=258.0,
    height=61.0
)

canvas.create_text(
    606.0,
    49.0,
    anchor="nw",
    text="2-D Area Selection",
    fill="#000000",
    font=("Courier New", 20 * -1)
)

canvas.create_text(
    560.0,
    88.0,
    anchor="nw",
    text="In this mode the antenna",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    108.0,
    anchor="nw",
    text="will scan a rectangular area",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    128.0,
    anchor="nw",
    text="of the skymap.",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    160.0,
    anchor="nw",
    text="Click the ‘Select Corners’",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    180.0,
    anchor="nw",
    text="button. Selecting this",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    200.0,
    anchor="nw",
    text="button will prompt the",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    220.0,
    anchor="nw",
    text="program to record the",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    240.0,
    anchor="nw",
    text="coordinates of the next two",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    260.0,
    anchor="nw",
    text="mouse clicks within the",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    280.0,
    anchor="nw",
    text="image.",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    312.0,
    anchor="nw",
    text="Select a lower left corner",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    332.0,
    anchor="nw",
    text="first and then an upper",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    352.0,
    anchor="nw",
    text="right corner.",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    383.0,
    anchor="nw",
    text="Then, select ‘Initiate",
    fill="#000000",
    font=("Courier New", 18 * -1)
)

canvas.create_text(
    560.0,
    403.0,
    anchor="nw",
    text="Scan’.",
    fill="#000000",
    font=("Courier New", 18 * -1)
)


path = "result.png"
img = ImageTk.PhotoImage(file=path)
canvas.create_image(275, 300, image=img)

'''panel = Label(window, image=img)
panel.pack(side="left")#, fill="both", expand="no")'''

'''canvas.create_rectangle(
    29.0,
    50.0,
    529.0,
    550.0,
    fill="#000000",
    outline="")
'''

window.resizable(False, False)
window.mainloop()
